class OPF_F {name = "C.S.A.T."; value="LT_OPF_F"; };
class OPF_G_F {name = "REDFOR Guerilla"; value="LT_OPF_G_F"; };
class IND_F {name = "A.A.F."; value="LT_IND_F"; };
class IND_G_F {name = "GREENFOR Guerilla"; value="LT_IND_G_F"; };
class OPF_T_F {name = "C.S.A.T. (Tanoa)"; value="LT_OPF_T_F"; };
class IND_C_F {name = "Syndikat"; value="LT_IND_C_F"; };
class NLDO_RU_VDV_76 {name = "Russian VDV 76"; value="LT_NLDO_RU_VDV_76"; };
class NLDO_RU_VDV_31 {name = "Russian VDV 31"; value="LT_NLDO_RU_VDV_31"; };
class NLDO_UA_UAF_95 {name = "Ukraine 95th inf bat"; value="LT_NLDO_UA_UAF_95"; };
class CUP_O_TK_INS {name = "Takistani Militia"; value="LT_CUP_O_TK_INS"; };
class CUP_O_TK {name = "Takistani Army"; value="LT_CUP_O_TK"; };
class CUP_O_CHDKZ {name = "ChDKZ"; value="LT_CUP_O_CHDKZ"; };
class CUP_O_SLA {name = "Sahrani Liberation Army"; value="LT_CUP_O_SLA"; };
class CUP_O_RU_EMR {name = "Russia (EMR)"; value="LT_CUP_O_RU_EMR"; };
class CUP_O_RU_FLORA {name = "Russia (Flora)"; value="LT_CUP_O_RU_FLORA"; };
class CUP_I_NAPA { name = "N.A.P.A."; value="LT_CUP_I_NAPA"; };
class CUP_I_RACS { name = "Royal Army Corp of Sahrani"; value="LT_CUP_I_RACS"; };
class CUP_I_TK_GUE { name = "Takistani Locals"; value="LT_CUP_I_TK_GUE"; };
class LT_CUP_I_PMC { name = "PMC"; value="LT_CUP_I_PMC"; };
class LT_CUP_AFR_REB { name = "African Rebels", value="LT_CUP_AFR_REB"; };
class CUP_AFR_ARMY { name = "African Army", value="CUP_AFR_ARMY"; };
class CUP_AFR_M_REB { name = "African Muslim Insurgents", value="CUP_AFR_M_REB"; };
class CUSTOM {name="Custom faction";value="LT_CUSTOM";};
