// filename 	".sqf"
// loadout name ""

// Attachments Primary weapon
lt_template_attach1        	 = 	 "ACE_acc_pointer_green"; // ir laser
lt_template_attach2        	 = 	 "CUP_acc_Flashlight"; // flashlight
lt_template_silencer1      	 = 	 "muzzle_snds_570"; // rifles
lt_template_silencer2      	 = 	 ""; // MG
lt_template_scope1         	 = 	 "CUP_optic_HoloBlack"; // normal scope
lt_template_scope2         	 = 	 ""; // scope sniper
lt_template_scope3         	 = 	 "";
lt_template_bipod1         	 = 	 "bipod_01_F_blk"; // MG
lt_template_bipod2         	 = 	 "";
lt_template_attachments    	 = 	 [lt_template_attach1, lt_template_scope1];

// Handgun attachements
lt_template_hg_silencer1         	 = 	 "";
lt_template_hg_scope1      	 = 	 "";
lt_template_hg_attachments         	 = 	 [];

// Assistant Automatic Rifleman, Medium MG assistant, UAV Operator, Rifleman
lt_template_rifle          	 = 	 "CUP_sgun_M1014";
lt_template_riflemag       	 = 	 "CUP_8Rnd_B_Beneli_74Slug";
lt_template_riflemag_t     	 = 	 "CUP_8Rnd_B_Beneli_74Pellets";

//Medic, Rifleman At
lt_template_carbine        	 = 	 "SMG_03_black";
lt_template_carbinemag     	 = 	 "50Rnd_570x28_SMG_03";
lt_template_carbinemag_tr    = 	 "50Rnd_570x28_SMG_03";

// Pilots, Vehicle crew, Submachinegunner
lt_template_smg    	 = 	 "SMG_03C_TR_black";
lt_template_smgmag         	 = 	 "50Rnd_570x28_SMG_03";
lt_template_smgmag_tr      	 = 	 "50Rnd_570x28_SMG_03";

// Commander, Squadleader, Fireteam leader, Spotter, Grenadier
lt_template_glrifle        	 = 	 "SMG_03C_TR_black";
lt_template_glriflemag     	 = 	 "50Rnd_570x28_SMG_03";
lt_template_glriflemag_tr          	 = 	 "50Rnd_570x28_SMG_03";
lt_template_glmag          	 = 	 "CUP_HandGrenade_M67";
lt_template_glsmokewhite           	 = 	 "SmokeShell";
lt_template_glsmokegreen           	 = 	 "SmokeShellGreen";
lt_template_glsmokered     	 = 	 "SmokeShellRed";
lt_template_glflarewhite           	 = 	 "Chemlight_blue";
lt_template_glflarered     	 = 	 "Chemlight_red";
lt_template_glflareyellow          	 = 	 "Chemlight_yellow";
lt_template_glflaregreen           	 = 	 "Chemlight_green";

// Commander, Squadleader, Automatic Rifleman, Medium Machinegunner, Designated Marksman, Sniper
lt_template_pistol         	 = 	 "hgun_P07_khk_F";
lt_template_pistolmag      	 = 	 "16Rnd_9x21_Mag";

// Automatic Rifleman
lt_template_AR     	 = 	 "CUP_arifle_M4A3_desert";
lt_template_ARmag          	 = 	 "CUP_30Rnd_556x45_Stanag";
lt_template_ARmag_tr       	 = 	 "30Rnd_556x45_Stanag_Tracer_Green";

// Medium MG Gunner
lt_template_MMG    	 = 	 "CUP_lmg_m249_para";
lt_template_MMGmag         	 = 	 "CUP_100Rnd_TE4_Green_Tracer_556x45_M249";
lt_template_MMGmag_tr      	 = 	 "CUP_100Rnd_TE4_Green_Tracer_556x45_M249";

// Designated Marksman
lt_template_DMrifle        	 = 	 "CUP_srifle_Mk12SPR";
lt_template_DMriflemag     	 = 	 "30Rnd_556x45_Stanag";

// Rifleman AT
lt_template_RAT    	 = 	 "CUP_launch_M136";
lt_template_RATmag1    	 = 	 "";
lt_template_RATmag2    	 = 	 "";

// Medium AT Gunner, Medium AT Gunner Assistant (alleen magazijnen)
lt_template_MAT    	 = 	 "CUP_launch_Javelin";
lt_template_MATmag1        	 = 	 "CUP_Javelin_M";
lt_template_MATmag2        	 = 	 "CUP_Javelin_M";

// Medium SAM Gunner, Medium SAM Gunner Assistant (alleen magazijnen)
lt_template_SAM    	 = 	 "CUP_launch_FIM92Stinger";
lt_template_SAMmag         	 = 	 "CUP_Stinger_M";

// Heavy AT Gunner, Heavy AT Gunner Assistant (alleen magazijnen
lt_template_HAT    	 = 	 "CUP_launch_Metis";
lt_template_HATmag1        	 = 	 "CUP_AT13_M";
lt_template_HATmag2        	 = 	 "CUP_AT13_M";

// Sniper
lt_template_SNrifle        	 = 	 "CUP_srifle_AWM_wdl";
lt_template_SNrifleMag     	 = 	 "CUP_5Rnd_86x70_L115A1";

// Grenades
lt_template_grenade        	 = 	 "HandGrenade";
lt_template_Mgrenade       	 = 	 "CUP_HandGrenade_M67";

// Static weapons
lt_template_baghmgg = "CUP_B_M2_Gun_Bag";
lt_template_baghmgag = "CUP_B_M2_Tripod_Bag";
lt_template_baghatg = "CUP_B_Tow_Gun_Bag";
lt_template_baghatag = "CUP_B_TOW_Tripod_Bag";
lt_template_bagmtrg = "CUP_B_M252_Gun_Bag";
lt_template_bagmtrag = "CUP_B_M252_Bipod_Bag";
